### ISSUE TITLE
HTTP average: request per minute metric always 0

### ISSUE THREAD

**Issue by robin-monnier** [keymetrics/keymetrics-support#132]
For some processes, the value is always 0.

**Comment by vmarchaud** [comment]
keymetrics/pmx related

**Comment by vmarchaud** [comment]
It should be working with the new module https://github.com/keymetrics/pm2-io-apm

**Comment by camparound-developers** [comment]
I have the same issue but i don't use pm2-io-apm, only pm2 as process manager for an express and a sails server. The counter for the express server delivers correct data, the counter for sails does not  (always 0) since i updated pm2 to version 3.0.0. It worked fine with pm2 v2.x (i don't remember the subversion). Any solution?
