### ISSUE TITLE
Interactions are not going through to dashboard

### ISSUE THREAD

**Issue by sebastiankade** [keymetrics/keymetrics-support#46]
Hey guys,

This isnt really an issue for github but couldnt find a support email. 

I'm using pm2 on my digital ocean box and wanted to add the awesome keymetrics but after running the setup command nothing is coming through and it still shows the setup screen.

I tried re-addeding my apps to pm2 and restarting but still nothing. 

Cheers

**Comment by Atelier-Morales** [comment]
Hi Sebastian,
Fernan from Keymetrics here. You can easily get in touch with the team via the intercom logo on the top-right corner of the screen (the round question mark next to your username). Just open it and start chatting with us. In the meantime, could you please give us your Keymetrics id, username or email so that we can see what is going on with your bucket? Thanks.

**Comment by sebastiankade** [comment]
hey @Atelier-Morales thanks for the reply, 

Intercom doesn't show up for me in the app actually:
![screen shot 2015-03-10 at 6 32 02 pm](https://cloud.githubusercontent.com/assets/400163/6570746/cd91acfc-c753-11e4-9a57-948ad8441ff7.png)

My account email is: sebastian@sumry.in

Appreciate the help

**Comment by jorge-d** [comment]
Hi @sebastiankade, could you tell us which browser do you use? Have you any browser plugin like noscript ? Do you see any Javascript error when you open your browser console?

Thanks,
